services:
  zitadel:
    restart: 'always'
    networks:
      - 'internal'
    image: 'ghcr.io/zitadel/zitadel:v2.56.0-rc.2'
    command: 'start-from-init --config /config.yaml --steps /init-steps.yaml --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    volumes:
      - "./zitadel/defaults.yaml:/config.yaml:ro"
      - "./zitadel/init-steps.yaml:/init-steps.yaml:ro"
      - "./zitadel/machine-key.json:/machinekey/zitadel-admin-sa.json:ro"
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  db:
    restart: 'always'
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zitadel
    networks:
      - 'internal'
    volumes:
      - ./../local/zitadel-db:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '5432:5432'

networks:
  internal: